export type EvidenceAssetType = "skill" | "llm_wiki" | "code_graph" | "chat_memory";
export type EvidenceAccessMode = "search" | "read" | "inject";
export interface TaskRun { run_id: string; team_id: string; agent_id: string; user_id: string; task_goal: string; status: string; code_version?: "before_evidence" | "after_evidence"; asset_mode?: "without_assets" | "with_assets"; asset_selection_mode?: "automatic" | "oracle" | "none"; [key: string]: unknown; }
export interface AssetAccess { access_id: string; run_id: string; asset_id: string; asset_type: EvidenceAssetType; version: number; content_digest?: string; mode: EvidenceAccessMode; source_candidate_id?: string; selection_score?: number; selection_reason?: string; token_estimate?: number; [key: string]: unknown; }
export interface AgentUsageClaim { claim_id: string; run_id: string; access_id: string; declared_usage: "used" | "not_used" | "uncertain"; purpose: string; [key: string]: unknown; }
export interface EvidenceState { recalled: boolean; selected: boolean; injected: boolean; declared_used: boolean; used: boolean; validation_passed: boolean; contributed: boolean; not_used: boolean; rejected: boolean; corrected: boolean; }
export interface DerivedAssetEvidence { access_id: string; asset_id: string; asset_type: EvidenceAssetType; name?: string; version: number; source_ref?: string; source_candidate_id?: string; applicability?: string; selection_score?: number; selection_reason?: string; token_estimate?: number; evidence: EvidenceState; decision_refs: string[]; file_refs: string[]; validation_refs: string[]; risks: string[]; evidence_gaps: string[]; }
export interface AssetEvidenceReceipt { run_id: string; revision: number; summary: Record<string, number>; assets: DerivedAssetEvidence[]; metrics: Record<string, number | undefined>; contribution_evidence: "insufficient" | "suggestive" | "causal"; [key: string]: unknown; }
export interface EvidenceSnapshot { run: TaskRun; accesses: AssetAccess[]; claims: AgentUsageClaim[]; events: unknown[]; behaviors: unknown[]; diffs: unknown[]; validations: unknown[]; reviews: unknown[]; evaluations: unknown[]; candidates: unknown[]; [key: string]: unknown; }
export interface CreateTaskRunRequest { team_id: string; agent_id: string; user_id: string; task_goal: string; [key: string]: unknown; }
export interface CandidateAsset { candidate_id: string; source_run_id: string; source_diff_ids: string[]; source_validation_ids: string[]; proposed_kind: "project_convention" | "failure_experience" | "skill" | "workflow" | "code_knowledge" | "product_knowledge"; applicability?: string; risks?: string[]; recommendation?: "publish" | "revise" | "deprecate" | "conflict"; supersedes_asset_id?: string; conflict_asset_ids?: string[]; deprecates_asset_ids?: string[]; version?: number; reviewer_decision?: string; published_asset_id?: string; content: string; confidence: number; review_required: true; status: "candidate" | "rejected" | "approved"; created_at: string; }
export interface EvaluationConfig { evaluation_group_id: string; code_version: "before_evidence" | "after_evidence"; asset_mode: "without_assets" | "with_assets"; asset_selection_mode?: "automatic" | "oracle" | "none"; }
export interface AssetEffectiveness { asset_id: string; asset_version: number; recalled: number; selected: number; injected: number; used: number; validated: number; contributed: number; corrected: number; task_successes: number; task_failures: number; successes: number; evaluations: number; positive_gain: number; negative_gain: number; neutral_gain: number; total_tokens: number; total_latency_ms: number; tool_calls: number; error_attempts: number; confidence: number; last_evaluated_at?: string; status: "insufficient" | "suggestive" | "causal" | "degraded"; }
