import { buildReceipt } from "./receipt-builder.js";
import { generateCandidate } from "./candidate-generator.js";
import { InMemoryEvidenceStore, type EvidenceRunFilter, type EvidenceRunPage, type EvidenceStore } from "./evidence-store.js";
import type { AccessMode, AgentUsageClaim, AssetAccess, AssetEvidenceReceipt, AssetType, Behavior, CandidateAsset, CodeDiff, CreateTaskRunInput, EvidenceEvent, EvidenceEventType, EvidenceSnapshot, Evaluation, Review, TaskRun, Validation } from "./types.js";
import { id, isoNow } from "./types.js";

const MAX = 10000;
function checkText(name: string, value: unknown, max = MAX) { if (typeof value !== "string" || value.length === 0 || value.length > max) throw new Error(`invalid ${name}`); }
function payloadJson(value: unknown) { return JSON.stringify(value); }

export class EvidenceService {
  constructor(public readonly store: EvidenceStore = new InMemoryEvidenceStore()) {}

  async createTaskRun(input: CreateTaskRunInput): Promise<TaskRun> {
    checkText("team_id", input.team_id, 200); checkText("agent_id", input.agent_id, 200); checkText("user_id", input.user_id, 200); checkText("task_goal", input.task_goal, 20000);
    const run: TaskRun = { ...input, run_id: id("run"), status: input.status ?? "running", created_at: isoNow(), run_kind: input.run_kind ?? "main", receipt_revision: 0 };
    const scope = input.idempotency_key && [input.team_id, input.agent_id, input.user_id, input.agent_source, input.session_id, input.execution_id, input.idempotency_key].join("\u0000");
    const { idempotency_key: _idempotencyKey, ...payload } = input;
    return (await this.store.createRunIdempotent(run, scope, payloadJson(payload))).run;
  }

  private async run(runId: string) { const run = await this.store.getRun(runId); if (!run) throw new Error("run not found"); return run; }
  private async open(runId: string) { const run = await this.run(runId); if (run.status !== "running") throw new Error("run is closed"); return run; }
  private async ensureAccess(runId: string, accessId: string) { const a = await this.store.getAccess(accessId); if (!a || a.run_id !== runId) throw new Error("access does not belong to run"); return a; }

  async recordAccess(runId: string, input: Omit<AssetAccess, "access_id" | "run_id" | "created_at">): Promise<AssetAccess> {
    const run = await this.open(runId); if (!Number.isInteger(input.version) || input.version < 0) throw new Error("invalid version");
    if (input.reader_team_id !== run.team_id || input.reader_agent_id !== run.agent_id || input.reader_user_id !== run.user_id) throw new Error("reader does not belong to run");
    const { idempotency_key, ...payload } = input;
    if (idempotency_key !== undefined) checkText("idempotency_key", idempotency_key, 500);
    const access: AssetAccess = { ...input, access_id: id("acc"), run_id: runId, created_at: isoNow() };
    const eventType: EvidenceEventType = input.mode === "inject" ? "asset_injected" : input.mode === "read" ? "asset_read" : "asset_recalled";
    return (await this.store.commitIngest("access", access, { run_id: runId, type: eventType, data: { access_id: access.access_id, asset_id: access.asset_id, version: access.version }, schema_version: 1, actor: { type: "proxy" }, occurred_at: access.created_at, idempotency_key: `access:${idempotency_key ?? access.access_id}` }, idempotency_key, payloadJson(payload))).value as AssetAccess;
  }
  recordAssetAccess(runId: string, input: Omit<AssetAccess, "access_id" | "run_id" | "created_at">) { return this.recordAccess(runId, input); }
  recordSelection(runId: string, accessId: string, reason?: string, tokenEstimate?: number) { return this.appendEvent(runId, "asset_selected", { access_id: accessId, reason, token_estimate: tokenEstimate }, `select:${accessId}:${tokenEstimate ?? ""}`); }
  recordInjection(runId: string, accessId: string, mode: "summary" | "full" | "tool" = "summary") { return this.appendEvent(runId, "asset_injected", { access_id: accessId, mode }, `inject:${accessId}:${mode}`); }

  async appendEvent(runId: string, type: EvidenceEventType, data: Record<string, unknown>, idempotencyKey: string, actor: EvidenceEvent["actor"] = { type: "proxy" }): Promise<EvidenceEvent> {
    const run = await this.run(runId); if (run.status !== "running" && !["correction_recorded", "review_recorded", "candidate_generated", "candidate_reviewed"].includes(type)) throw new Error("run is closed"); checkText("idempotency_key", idempotencyKey, 500);
    if (!data || typeof data !== "object" || Array.isArray(data) || JSON.stringify(data).length > 100_000) throw new Error("invalid event data");
    const required = (key: string) => { if (typeof data[key] !== "string" || !(data[key] as string).trim()) throw new Error(`${key} required`); };
    if (["asset_selected", "asset_injected", "asset_read", "asset_recalled", "agent_declared", "intent_declared"].includes(type)) required("access_id");
    if (["behavior_observed"].includes(type)) required("behavior_id");
    if (["diff_recorded"].includes(type)) required("diff_id");
    if (["validation_recorded"].includes(type)) required("validation_id");
    if (["review_recorded"].includes(type)) required("review_id");
    if (["evaluation_recorded"].includes(type)) required("evaluation_id");
    if (["candidate_generated"].includes(type)) required("candidate_id");
    if (type === "diff_unavailable") required("reason");
    if (["asset_selected", "asset_injected", "asset_read", "asset_recalled", "agent_declared", "intent_declared", "correction_recorded"].includes(type)) { const accessId = data.access_id; if (typeof accessId !== "string") throw new Error("access_id required"); const access = await this.ensureAccess(runId, accessId); if (data.asset_id !== undefined && data.asset_id !== access.asset_id) throw new Error("asset snapshot mismatch"); if (data.version !== undefined && data.version !== access.version) throw new Error("asset snapshot mismatch"); }
    if (type === "correction_recorded" && typeof data.original_event_id !== "string") throw new Error("original_event_id required");
    return this.store.appendEvent({ run_id: runId, type, data, schema_version: 1, actor, occurred_at: typeof data.occurred_at === "string" ? data.occurred_at : isoNow(), idempotency_key: idempotencyKey });
  }
  appendEvidenceEvent(runId: string, type: EvidenceEventType, data: Record<string, unknown>, idempotencyKey: string, actor?: EvidenceEvent["actor"]) { return this.appendEvent(runId, type, data, idempotencyKey, actor); }

  async recordClaim(runId: string, input: Omit<AgentUsageClaim, "claim_id" | "run_id" | "created_at">): Promise<AgentUsageClaim> {
    await this.open(runId); await this.ensureAccess(runId, input.access_id); checkText("purpose", input.purpose, 4000);
    for (const ref of [...(input.behavior_refs ?? []), ...(input.diff_refs ?? []), ...(input.validation_refs ?? []), ...(input.decision_refs ?? [])]) checkText("reference", ref, 300);
    const { idempotency_key, ...payload } = input; if (idempotency_key !== undefined) checkText("idempotency_key", idempotency_key, 500);
    const claim = { ...input, claim_id: id("claim"), run_id: runId, created_at: isoNow() };
    return (await this.store.commitIngest("claim", claim, { run_id: runId, type: "agent_declared", data: { access_id: claim.access_id, claim_id: claim.claim_id, declared_usage: claim.declared_usage }, schema_version: 1, actor: { type: "agent" }, occurred_at: claim.created_at, idempotency_key: `claim:${idempotency_key ?? claim.claim_id}` }, idempotency_key, payloadJson(payload))).value as AgentUsageClaim;
  }

  async recordBehavior(runId: string, input: Omit<Behavior, "behavior_id" | "run_id" | "created_at">) { await this.open(runId); checkText("tool_name", input.tool_name, 500); if (input.external_tool_use_id !== undefined) checkText("external_tool_use_id", input.external_tool_use_id, 500); if (input.phase !== undefined && input.phase !== "intent" && input.phase !== "execution") throw new Error("invalid behavior phase"); if (input.parent_behavior_id !== undefined) { checkText("parent_behavior_id", input.parent_behavior_id, 300); if (!(await this.store.listBehaviors(runId)).some(x => x.behavior_id === input.parent_behavior_id)) throw new Error("parent behavior does not belong to run"); } const { idempotency_key, ...payload } = input; if (idempotency_key !== undefined) checkText("idempotency_key", idempotency_key, 500); const v = { ...input, behavior_id: id("beh"), run_id: runId, created_at: isoNow() }; return (await this.store.commitIngest("behavior", v, { run_id: runId, type: "behavior_observed", data: { behavior_id: v.behavior_id }, schema_version: 1, actor: { type: "proxy" }, occurred_at: v.created_at, idempotency_key: `behavior:${idempotency_key ?? v.behavior_id}` }, idempotency_key, payloadJson(payload))).value as Behavior; }
  async recordDiff(runId: string, input: Omit<CodeDiff, "diff_id" | "run_id" | "created_at">) { await this.open(runId); const { idempotency_key, ...payload } = input; if (idempotency_key !== undefined) checkText("idempotency_key", idempotency_key, 500); const v = { ...input, diff_id: id("diff"), run_id: runId, created_at: isoNow() }; return (await this.store.commitIngest("diff", v, { run_id: runId, type: "diff_recorded", data: { diff_id: v.diff_id }, schema_version: 1, actor: { type: "proxy" }, occurred_at: v.created_at, idempotency_key: `diff:${idempotency_key ?? v.diff_id}` }, idempotency_key, payloadJson(payload))).value as CodeDiff; }
  async recordValidation(runId: string, input: Omit<Validation, "validation_id" | "run_id" | "created_at">) {
    await this.open(runId); checkText("command", input.command, 4000);
    if (typeof input.passed !== "boolean") throw new Error("passed must be a boolean"); if (input.exit_code !== undefined && (!Number.isInteger(input.exit_code) || input.exit_code < 0)) throw new Error("invalid exit code"); if (input.passed && input.exit_code !== 0) throw new Error("passed validation must have exit code 0"); checkText("validation_type", input.validation_type, 200);
    const [claims, behaviors, diffs] = await Promise.all([this.store.listClaims(runId), this.store.listBehaviors(runId), this.store.listDiffs(runId)]);
    if ((input.claim_refs ?? []).some((r) => !claims.some((x) => x.claim_id === r)) || (input.behavior_refs ?? []).some((r) => !behaviors.some((x) => x.behavior_id === r)) || (input.diff_refs ?? []).some((r) => !diffs.some((x) => x.diff_id === r))) throw new Error("validation reference does not belong to run");
    const { idempotency_key, ...payload } = input; if (idempotency_key !== undefined) checkText("idempotency_key", idempotency_key, 500); const v = { ...input, validation_id: id("val"), run_id: runId, created_at: isoNow() }; return (await this.store.commitIngest("validation", v, { run_id: runId, type: "validation_recorded", data: { validation_id: v.validation_id, passed: v.passed }, schema_version: 1, actor: { type: "proxy" }, occurred_at: v.created_at, idempotency_key: `validation:${idempotency_key ?? v.validation_id}` }, idempotency_key, payloadJson(payload))).value as Validation;
  }
  async recordReview(runId: string, input: Omit<Review, "review_id" | "run_id" | "created_at">) { await this.run(runId); await this.ensureAccess(runId, input.access_id); if (!(["support", "not_support", "uncertain"] as const).includes(input.decision)) throw new Error("invalid review decision"); checkText("reason", input.reason, 10000); for (const ref of [...(input.behavior_refs ?? []), ...(input.diff_refs ?? []), ...(input.decision_refs ?? [])]) checkText("reference", ref, 300); const [behaviors, diffs, claims, validations] = await Promise.all([this.store.listBehaviors(runId), this.store.listDiffs(runId), this.store.listClaims(runId), this.store.listValidations(runId)]); if ((input.behavior_refs ?? []).some((r) => !behaviors.some((x) => x.behavior_id === r)) || (input.diff_refs ?? []).some((r) => !diffs.some((x) => x.diff_id === r))) throw new Error("review reference does not belong to run"); if (input.decision === "support") { const evidenceRefs = [...(input.behavior_refs ?? []), ...(input.diff_refs ?? [])]; if (!evidenceRefs.length) throw new Error("support review requires behavior or diff evidence"); const linkedClaimIds = claims.filter(x => x.access_id === input.access_id).map(x => x.claim_id); const linked = (ref: string) => claims.some(x => x.access_id === input.access_id && ((x.behavior_refs ?? []).includes(ref) || (x.diff_refs ?? []).includes(ref))) || validations.some(v => (v.claim_refs ?? []).some(claimId => linkedClaimIds.includes(claimId)) && ((v.behavior_refs ?? []).includes(ref) || (v.diff_refs ?? []).includes(ref))); if (evidenceRefs.some(ref => !linked(ref))) throw new Error("review evidence is not linked to this asset claim"); } const v = { ...input, review_id: id("review"), run_id: runId, created_at: isoNow() }; const review = await this.store.commitReview(v, { run_id: runId, type: "review_recorded", data: { review_id: v.review_id, access_id: v.access_id, decision: v.decision }, schema_version: 1, actor: { type: "user", id: input.reviewer_user_id }, occurred_at: isoNow(), idempotency_key: `review:${v.review_id}` }); await this.materializeReceipt(runId); return review; }
  /** Public ingestion cannot assert independent causality: that flag is reserved for a trusted evaluator. */
  async recordEvaluation(runId: string, input: Omit<Evaluation, "evaluation_id" | "run_id" | "created_at" | "independent_causal_evidence">) { await this.open(runId); const v = { ...input, independent_causal_evidence: false, evaluation_id: id("eval"), run_id: runId, created_at: isoNow() }; await this.store.addEvaluation(v); await this.appendEvent(runId, "evaluation_recorded", { evaluation_id: v.evaluation_id }, `evaluation:${v.evaluation_id}`); return v; }
  async recordCorrection(runId: string, input: { original_event_id: string; access_id: string; reason: string; actor_id: string }) {
    const events = await this.store.listEvents(runId); const original = events.find(e => e.event_id === input.original_event_id); if (!original) throw new Error("original event not found"); if (original.data.access_id !== input.access_id) throw new Error("original event does not belong to access");
    await this.ensureAccess(runId, input.access_id); checkText("reason", input.reason, 10000);
    const event = await this.appendEvent(runId, "correction_recorded", input, `correction:${input.original_event_id}:${input.actor_id}`, { type: "user", id: input.actor_id });
    const run = await this.run(runId); await this.store.updateRun(runId, { receipt_revision: (run.receipt_revision ?? 0) + 1 }); await this.materializeReceipt(runId); return event;
  }

  async getSnapshot(runId: string): Promise<EvidenceSnapshot> { const run = await this.run(runId); return { run, accesses: await this.store.listAccesses(runId), claims: await this.store.listClaims(runId), events: await this.store.listEvents(runId), behaviors: await this.store.listBehaviors(runId), diffs: await this.store.listDiffs(runId), validations: await this.store.listValidations(runId), reviews: await this.store.listReviews(runId), evaluations: await this.store.listEvaluations(runId), candidates: await this.store.listCandidates(runId), receipt: undefined }; }
  listTaskRuns(filter: EvidenceRunFilter): Promise<EvidenceRunPage> { return this.store.listRuns(filter); }
  async reviewCandidate(runId: string, candidateId: string, status: "approved" | "rejected", reason: string, reviewerUserId: string): Promise<CandidateAsset> { await this.run(runId); checkText("reason", reason, 10000); const candidate = (await this.store.listCandidates(runId)).find(x => x.candidate_id === candidateId); if (!candidate) throw new Error("candidate does not belong to run"); return this.store.commitCandidateReview(runId, candidateId, status, { run_id: runId, type: "candidate_reviewed", data: { candidate_id: candidateId, status, reason, reviewer_user_id: reviewerUserId }, schema_version: 1, actor: { type: "user", id: reviewerUserId }, occurred_at: isoNow(), idempotency_key: `candidate-review:${candidateId}` }); }
  private async materializeReceipt(runId: string): Promise<AssetEvidenceReceipt> { const s = await this.getSnapshot(runId); const receipt = buildReceipt(s.run, s.accesses, s.claims, s.events, s.behaviors, s.diffs, s.validations, s.reviews, s.evaluations, s.run.receipt_revision || 1); await this.store.saveReceipt(receipt); return receipt; }
  async getReceipt(runId: string, revision?: number): Promise<AssetEvidenceReceipt> { const run = await this.run(runId); const target = revision ?? (run.receipt_revision || 1); if (!Number.isInteger(target) || target < 1) throw new Error("invalid receipt revision"); if (revision === undefined && run.status === "running") { const s = await this.getSnapshot(runId); return buildReceipt(s.run, s.accesses, s.claims, s.events, s.behaviors, s.diffs, s.validations, s.reviews, s.evaluations, target); } const saved = await this.store.getReceipt(runId, target); if (saved) return saved; if (target !== (run.receipt_revision || 1)) throw new Error("receipt revision not found"); if (!run.receipt_revision) { const s = await this.getSnapshot(runId); return buildReceipt(s.run, s.accesses, s.claims, s.events, s.behaviors, s.diffs, s.validations, s.reviews, s.evaluations, target); } return this.materializeReceipt(runId); }
  getEvidenceReceipt(runId: string) { return this.getReceipt(runId); }
  async closeTaskRun(runId: string, closeReason?: string, idempotencyKey?: string, finalStatus: "completed" | "cancelled" | "abandoned" = "completed"): Promise<AssetEvidenceReceipt> { const run = await this.run(runId); const closeKey = `close:${idempotencyKey ?? runId}`; if (run.status !== "running") { const existing = (await this.store.listEvents(runId)).find(x => x.type === "task_run_closed" && x.idempotency_key === closeKey); if (existing && existing.data.close_reason === closeReason) return this.getReceipt(runId); throw new Error("run is closed"); } if (idempotencyKey !== undefined) checkText("idempotency_key", idempotencyKey, 500); const candidate = finalStatus === "completed" ? generateCandidate({ run, claims: await this.store.listClaims(runId), diffs: await this.store.listDiffs(runId), validations: await this.store.listValidations(runId), reviews: await this.store.listReviews(runId) }) : undefined; const now = isoNow(), nextRevision = Math.max(1, (run.receipt_revision ?? 0) + 1); await this.store.commitClose(runId, candidate, [...(candidate ? [{ run_id: runId, type: "candidate_generated" as const, data: { candidate_id: candidate.candidate_id }, schema_version: 1, actor: { type: "system" as const }, occurred_at: now, idempotency_key: `candidate:${candidate.candidate_id}` }] : []), { run_id: runId, type: "task_run_closed", data: { close_reason: closeReason, final_status: finalStatus }, schema_version: 1, actor: { type: "system" }, occurred_at: now, idempotency_key: closeKey }], { status: finalStatus, close_reason: closeReason, closed_at: now, receipt_revision: nextRevision }); return this.materializeReceipt(runId); }
}
